title = "SuperCommand"
gitRepoUrl = "https://github.com/xSwezan/SuperCommand"
gitSourceBranch = "main"

classorder = [
	"SuperCommand",
	"Group",
	"Type",
	"Operator"
]

[home]
enabled = true
includeReadme = false

[navbar.logo]
alt = "SuperCommand"
src = "Icon.png"

[docusaurus]
tagline = "Powerful Chat Command module with Rich API!"